config/routes.rb
Rails.application.routes.draw do
  constraints(host: /www2\.|\.education\./) do
    match "/(*path)" => redirect { |_, req| "#{Settings.dfe_signin.base_url}#{req.fullpath}" },
          via: %i[get post put]
  end

  get :ping, controller: :heartbeat
  get :healthcheck, controller: :heartbeat
  get :sha, controller: :heartbeat

  # Old links
  get "/signin", to: redirect("/sign-in")
  get "/signout", to: redirect("/sign-out")

  get "/sign-in", to: "sign_in#index"
  get "/sign-out", to: "sessions#signout"

  if AuthenticationService.magic_link?
    post "/send_magic_link", to: "sessions#send_magic_link"
    get "/magic_link_sent", to: "sessions#magic_link_sent"
    get "/signin_with_magic_link", to: "sessions#create_by_magic", as: "signin_with_magic_link"
  elsif AuthenticationService.persona?
    get "/personas", to: "personas#index"
    post "/auth/developer/callback", to: "sessions#create"
    get "/auth/developer/signout", to: "sessions#destroy"
  else
    get "/auth/dfe/callback", to: "sessions#create"
    get "/auth/dfe/signout", to: "sessions#destroy"
  end

  get "/auth/failure", to: "sessions#failure"

  root to: "providers#index"
  get "/organisations", to: redirect("/")

  resources :notifications, path: "/notifications", controller: "notifications", only: %i[index update]

  resources :access_requests, path: "/access-requests", controller: "access_requests", only: %i[new index create] do
    member do
      post :approve
      get :confirm
      get "/inform-publisher", to: "access_requests#inform_publisher"
    end
  end

  get "organisations-support-page", to: "organisations#index"

  resources :providers, path: "organisations", param: :code do
    # Redirect year-less URLs to current recruitment cycle
    get "/locations", to: redirect("/organisations/%{provider_code}/#{Settings.current_cycle}/locations")
    get "/locations/:location_id/edit", to: redirect("/organisations/%{provider_code}/#{Settings.current_cycle}/locations/%{location_id}/edit")
    get "/locations/new", to: redirect("/organisations/%{provider_code}/#{Settings.current_cycle}/locations/new")
    get "/courses", to: redirect("/organisations/%{provider_code}/#{Settings.current_cycle}/courses")
    get "/courses/:course_code", to: redirect("/organisations/%{provider_code}/#{Settings.current_cycle}/courses/%{course_code}")
    get "/courses/:course_code/locations", to: redirect("/organisations/%{provider_code}/#{Settings.current_cycle}/courses/%{course_code}/locations")
    get "/courses/:course_code/vacancies", to: redirect("/organisations/%{provider_code}/#{Settings.current_cycle}/courses/%{course_code}/vacancies")
    get "/courses/:course_code/about", to: redirect("/organisations/%{provider_code}/#{Settings.current_cycle}/courses/%{course_code}/about")
    get "/courses/:course_code/details", to: redirect("/organisations/%{provider_code}/#{Settings.current_cycle}/courses/%{course_code}/details")
    get "/courses/:course_code/fees", to: redirect("/organisations/%{provider_code}/#{Settings.current_cycle}/courses/%{course_code}/fees")
    get "/courses/:course_code/salary", to: redirect("/organisations/%{provider_code}/#{Settings.current_cycle}/courses/%{course_code}/salary")
    get "/courses/:course_code/requirements", to: redirect("/organisations/%{provider_code}/#{Settings.current_cycle}/courses/%{course_code}/requirements")
    get "/courses/:course_code/withdraw", to: redirect("/organisations/%{provider_code}/#{Settings.current_cycle}/courses/%{course_code}/withdraw")
    get "/courses/:course_code/delete", to: redirect("/organisations/%{provider_code}/#{Settings.current_cycle}/courses/%{course_code}/delete")
    get "/courses/:course_code/preview", to: redirect("/organisations/%{provider_code}/#{Settings.current_cycle}/courses/%{course_code}/preview")

    get "/request-access", on: :member, to: "providers/access_requests#new"
    post "/request-access", on: :member, to: "providers/access_requests#create"

    get "/users", on: :member, to: "providers/users#index"

    resource :ucas_contacts, path: "ucas-contacts", on: :member, only: %i[show] do
      get "/alerts", on: :member, to: "ucas_contacts#alerts"
      patch "/alerts", on: :member, to: "ucas_contacts#update_alerts"
    end

    resources :contacts, only: %i[edit update]

    resources :recruitment_cycles, param: :year, constraints: { year: /#{Settings.current_cycle}|#{Settings.current_cycle + 1}/ }, path: "", only: :show do
      get "/details", on: :member, to: "providers#details"
      get "/contact", on: :member, to: "providers#contact"
      put "/contact", on: :member, to: "providers#update"
      get "/about", on: :member, to: "providers#about"
      put "/about", on: :member, to: "providers#update"
      post "/publish", on: :member, to: "providers#publish"
      get "/training-providers", on: :member, to: "providers#training_providers"
      get "/training-providers-courses", on: :member, to: "training_providers_courses#index", as: "download_training_providers_courses"
      get "/visas", to: "providers/visas#edit"
      post "/visas", to: "providers/visas#update"
      get "/references", to: "providers/references#edit"
      post "/references", to: "providers/references#update"

      resource :training_providers, path: "/training-providers", on: :member, param: :code, only: [], as: "" do
        get "/:training_provider_code/courses", to: "providers#training_provider_courses", as: "training_provider_courses"
      end

      resource :courses, only: %i[create] do
        resource :outcome, on: :member, only: %i[new], controller: "courses/outcome" do
          get "continue"
        end
        resource :entry_requirements, on: :member, only: %i[new], controller: "courses/entry_requirements", path: "entry-requirements" do
          get "continue"
        end
        resource :study_mode, on: :member, only: %i[new], controller: "courses/study_mode", path: "full-part-time" do
          get "continue"
        end
        resource :level, on: :member, only: %i[new], controller: "courses/level" do
          get "continue"
        end
        resource :locations, on: :member, only: %i[new], controller: "courses/sites" do
          get "back"
          get "continue"
        end
        resource :start_date, on: :member, only: %i[new], controller: "courses/start_date", path: "start-date" do
          get "continue"
        end
        resource :applications_open, on: :member, only: %i[new], controller: "courses/applications_open", path: "applications-open" do
          get "continue"
        end
        resource :age_range, on: :member, only: %i[new], controller: "courses/age_range", path: "age-range" do
          get "continue"
        end
        resource :subjects, on: :member, only: %i[new], controller: "courses/subjects", path: "subjects" do
          get "continue"
        end
        resource :modern_languages, on: :member, only: %i[new], controller: "courses/modern_languages", path: "modern-languages" do
          get "back"
          get "continue"
        end
        resource :apprenticeship, on: :member, only: %i[new], controller: "courses/apprenticeship" do
          get "continue"
        end
        resource :accredited_body, on: :member, only: %i[new], controller: "courses/accredited_body", path: "accredited-body" do
          get "continue"
          get "search_new"
        end
        resource :fee_or_salary, on: :member, only: %i[new], controller: "courses/fee_or_salary", path: "fee-or-salary" do
          get "continue"
        end
        get "confirmation"
      end

      resources :courses, param: :code do
        delete "/", on: :member, to: "courses#destroy"

        get "/vacancies", on: :member, to: "courses/vacancies#edit"
        put "/vacancies", on: :member, to: "courses/vacancies#update"
        get "/details", on: :member, to: "courses#details"

        get "/about", on: :member, to: "courses#about"
        patch "/about", on: :member, to: "courses#update"
        get "/requirements", on: :member, to: "courses#requirements"
        patch "/requirements", on: :member, to: "courses#update"
        get "/fees", on: :member, to: "courses#fees"
        patch "/fees", on: :member, to: "courses#update"
        get "/salary", on: :member, to: "courses#salary"
        patch "/salary", on: :member, to: "courses#update"

        get "/withdraw", on: :member, to: "courses#withdraw_course"
        post "/withdraw", on: :member, to: "courses#withdraw_course"

        get "/delete", on: :member, to: "courses#delete"
        get "/preview", on: :member, to: "courses#preview"
        get "/locations", on: :member, to: "courses/sites#edit"
        put "/locations", on: :member, to: "courses/sites#update"
        get "/publish", on: :member, to: "courses#details"
        post "/publish", on: :member, to: "courses#publish"

        get "/title", on: :member, to: "courses/title#edit"
        put "/title", on: :member, to: "courses/title#update"

        get "/entry-requirements", on: :member, to: "courses/entry_requirements#edit"
        put "/entry-requirements", on: :member, to: "courses/entry_requirements#update"

        get "/outcome", on: :member, to: "courses/outcome#edit"
        put "/outcome", on: :member, to: "courses/outcome#update"

        get "/accredited-body", on: :member, to: "courses/accredited_body#edit"
        put "/accredited-body", on: :member, to: "courses/accredited_body#update"
        get "/accredited-body/search", on: :member, to: "courses/accredited_body#search"

        get "/subjects", on: :member, to: "courses/subjects#edit"
        put "/subjects", on: :member, to: "courses/subjects#update"

        get "/modern-languages", on: :member, to: "courses/modern_languages#edit"
        put "/modern-languages", on: :member, to: "courses/modern_languages#update"

        get "/age-range", on: :member, to: "courses/age_range#edit"
        put "/age-range", on: :member, to: "courses/age_range#update"

app/controllers/courses/accredited_body_controller.rb
module Courses
  class AccreditedBodyController < ApplicationController
    before_action :build_course_params, only: :continue
    include CourseBasicDetailConcern

    decorates_assigned :provider

    def edit
      build_provider
    end

    def continue
      code = course_params[:accredited_body_code]
      query = @accredited_body

      @errors = errors_for_search_query(code, query)

      if @errors.present?
        render :new
      elsif other_selected_with_no_autocompleted_code?(code)
        redirect_to(
          search_new_provider_recruitment_cycle_courses_accredited_body_path(
            query: @accredited_body,
            course: course_params,
          ),
        )
      else
        params[:course][:accredited_body_code] = @autocompleted_provider_code if @autocompleted_provider_code.present?
        super
      end
    end

    def search_new
      # These are not before_action hooks as they conflict with hooks
      # defined within the CourseBasicDetailConcern and cannot be overridden
      # without causing failures in other routes in this controller
      build_new_course
      build_provider
      build_previous_course_creation_params
      @query = params[:query]
      @provider_suggestions = ProviderSuggestion.suggest_any_accredited_body(@query)
    rescue JsonApiClient::Errors::ClientError => e
      @errors = e
    end

    def update
      build_provider
      code = update_course_params[:accredited_body_code]
      query = update_course_params[:accredited_body]

      @errors = errors_for_search_query(code, query)
      return render :edit if @errors.present?

      if update_params[:accredited_body_code] == "other"
        redirect_to_provider_search
      elsif @course.update(update_params)
        redirect_to_update_successful
      else
        @errors = @course.errors.messages
        render :edit
      end
    end

    def search
      build_course
      @query = params[:query]
      @provider_suggestions = ProviderSuggestion.suggest_any_accredited_body(@query)
    rescue JsonApiClient::Errors::ClientError => e
      @errors = e
    end

  private

    def build_provider
      @provider = Provider
                    .includes(:sites)
                    .where(recruitment_cycle_year: params[:recruitment_cycle_year])
                    .find(params[:provider_code])
                    .first
    end

    def error_keys
      [:accredited_body_code]
    end

    def redirect_to_provider_search
      redirect_to(
        accredited_body_search_provider_recruitment_cycle_course_path(
          @course.provider_code,
          @course.recruitment_cycle_year,
          @course.course_code,
          query: update_course_params[:accredited_body],
        ),
      )
    end

    def redirect_to_update_successful
      flash[:success] = "Your changes have been saved"
      redirect_to(
        details_provider_recruitment_cycle_course_path(
          @course.provider_code,
          @course.recruitment_cycle_year,
          @course.course_code,
        ),
      )
    end

    def current_step
      :accredited_body
    end

    def build_course_params
      @accredited_body = params[:course].delete(:accredited_body)
      @autocompleted_provider_code = params[:course].delete(:autocompleted_provider_code)
    end

    def errors_for_search_query(code, query)
      errors = {}

      if other_selected_with_no_autocompleted_code?(code) && query.length < 2
        errors = { accredited_body: ["Accredited body search too short, enter 2 or more characters"] }
      elsif code.blank?
        errors = { accredited_body_code: ["Pick an accredited body"] }
      end

      errors
    end

    def build_course
      @course = Course
        .where(recruitment_cycle_year: params[:recruitment_cycle_year])
        .where(provider_code: params[:provider_code])
        .includes(:accrediting_provider)
        .find(params[:code])
        .first
    end

    def update_course_params
      params.require(:course).permit(
        :autocompleted_provider_code,
        :accredited_body_code,
        :accredited_body,
      )
    end

    def update_params
      autocompleted_code = update_course_params[:autocompleted_provider_code]
      code = update_course_params[:accredited_body_code]

      {
        accredited_body_code: autocompleted_code.presence || code,
      }
    end

    def other_selected_with_no_autocompleted_code?(code)
      code == "other" && @autocompleted_provider_code.blank?
    end
  end
end

app/controllers/courses/age_range_controller.rb
module Courses
  class AgeRangeController < ApplicationController
    include CourseBasicDetailConcern
    decorates_assigned :course
    before_action :build_course, only: %i[edit update]

    def edit
      if params[:display_errors] == "true"
        form_object.valid?
      end

      render locals: { form_object: form_object }
    end

    def update
      if form_object.valid?
        flash[:success] = "Your changes have been saved"

        update_age_range_param

        if @course.update(course_params)
          redirect_to(
            details_provider_recruitment_cycle_course_path(
              @course.provider_code,
              @course.recruitment_cycle_year,
              @course.course_code,
            ),
          )
        end
      else
        render :edit, locals: { form_object: form_object }
      end
    end

  private

    def age_range_presets
      @course.meta["edit_options"]["age_range_in_years"]
    end

    def form_object
      @form_object ||= AgeRangeForm.new(permitted_params.merge(presets: age_range_presets))
    end

    def permitted_params
      if params[:course]
        (params[:course] || ActionController::Parameters.new).permit(:age_range_in_years, :course_age_range_in_years_other_from, :course_age_range_in_years_other_to)
      else
        @course.attributes.select { |k, _v| %w[age_range_in_years course_age_range_in_years_other_from course_age_range_in_years_other_to].include?(k) }
      end
    end

    def error_keys
      [:age_range_in_years]
    end

    def update_age_range_param
      params[:course][:age_range_in_years] = "#{age_from_param}_to_#{age_to_param}" if valid_custom_age_range?
    end

    def valid_custom_age_range?
      age_from_param.present? && age_to_param.present? && age_range_is_other?
    end

    def age_to_param
      course_param.dig(:course_age_range_in_years_other_to)
    end

    def age_from_param
      course_param.dig(:course_age_range_in_years_other_from)
    end

    def age_range_param
      course_param.dig(:age_range_in_years)
    end

    def age_range_is_other?
      age_range_param == "other"
    end

    def course_param
      params.dig(:course)
    end

    def current_step
      :age_range
    end

    def build_course
      @course = Course
        .where(recruitment_cycle_year: params[:recruitment_cycle_year])
        .where(provider_code: params[:provider_code])
        .find(params[:code])
        .first
    end
  end
end

app/controllers/courses/apprenticeship_controller.rb
module Courses
  class ApprenticeshipController < ApplicationController
    include CourseBasicDetailConcern

  private

    def current_step
      :apprenticeship
    end

    def error_keys
      %i[funding_type program_type]
    end
  end
end

app/controllers/courses/fee_or_salary_controller.rb
module Courses
  class FeeOrSalaryController < ApplicationController
    include CourseBasicDetailConcern

  private

    def current_step
      :fee_or_salary
    end

    def error_keys
      %i[funding_type program_type]
    end
  end
end

app/controllers/courses/level_controller.rb
module Courses
  class LevelController < ApplicationController
    include CourseBasicDetailConcern

  private

    def error_keys
      [:level]
    end

    def current_step
      :level
    end
  end
end

app/views/courses/sites/edit.html.erb
<% content_for :page_title, title_with_error_prefix("Pick the locations for this course – #{course.name_and_code}", @errors.present?) %>

<% content_for :before_content do %>
  <%= govuk_back_link_to(details_provider_recruitment_cycle_course_path(@provider.provider_code, course.recruitment_cycle_year, course.course_code)) %>
<% end %>

<% if @errors.present? %>
  <div class="govuk-error-summary" aria-labelledby="error-summary-title" role="alert" tabindex="-1" data-module="govuk-error-summary" data-ga-event-form="error">
    <h2 class="govuk-error-summary__title" id="error-summary-title">
      <%= @errors.first %>
    </h2>
    <div class="govuk-error-summary__body">
      <p class="govuk-body" data-error-message="Removing all locations would prevent people from applying to this course">
        Removing all locations would prevent people from applying to this course.
        If you want to close applications, you can
        <%= govuk_link_to "edit the vacancies for this course", vacancies_provider_recruitment_cycle_course_path(code: course.course_code) %>.
      </p>
    </div>
  </div>
<% end %>

<h1 class="govuk-heading-l">
  <span class="govuk-caption-l"><%= course.name_and_code %></span>
  Pick the locations for this course
</h1>

<div class="govuk-grid-row">
  <div class="govuk-grid-column-two-thirds">
    <p class="govuk-body govuk-body govuk-!-margin-bottom-6"><%= govuk_link_to "Manage all your locations", provider_recruitment_cycle_sites_path(@provider.provider_code), data: { qa: "course__manage_provider_locations_link" } %> to add to or edit this list.</p>

    <%= form_for course, url: locations_provider_recruitment_cycle_course_path(@provider.provider_code, course.recruitment_cycle_year, course.course_code), method: :put do |form| %>
      <div class="govuk-form-group">
        <div class="govuk-checkboxes">
          <%= form.fields_for :site_statuses, @provider.sites.sort_by(&:location_name) do |sf| %>
            <% site = sf.object %>
            <div class="govuk-checkboxes__item">
              <%= sf.check_box "selected", checked: course.has_site?(site), class: "govuk-checkboxes__input" %>
              <%= sf.label "selected", class: "govuk-label govuk-checkboxes__label"  do %>
                <strong><%= site.location_name %></strong>
              <% end %>
              <span class="govuk-hint govuk-checkboxes__hint">
                <%= site.full_address %>
              </span>
            </div>
          <% end %>
        </div>
      </div>

      <%= form.submit course.is_running? ? "Save and publish changes" : "Save",
        class: "govuk-button", data: { qa: "course__save" } %>
    <% end %>
  </div>
</div>

app/views/courses/sites/new.html.erb
<% content_for :page_title, title_with_error_prefix("Pick the locations for this course", @errors && @errors.any?) %>

<% content_for :before_content do %>
  <%= govuk_back_link_to(@back_link_path) %>
<% end %>

<%= render "shared/errors" %>

<%= form_for course,
  url: continue_provider_recruitment_cycle_courses_locations_path(@provider.provider_code, course.recruitment_cycle_year, course.course_code),
  method: :get do |form| %>
  <%= render "courses/new_fields_holder", form: form, except_keys: [:sites_ids] do |fields| %>
    <%= render "shared/error_wrapper", error_keys: [:sites], data_qa: "course__sites" do %>
      <fieldset class="govuk-fieldset">
        <legend class="govuk-fieldset__legend govuk-fieldset__legend--l">
          <h1 class="govuk-fieldset__heading" data-qa="page-heading">
            Pick the locations for this course
          </h1>
        </legend>
        <%= render "shared/error_messages", error_keys: [:sites] %>
        <div class="govuk-form-group govuk-!-margin-top-2">
          <div class="govuk-checkboxes">
            <%= fields.fields_for :site_statuses, @provider.sites.sort_by(&:location_name) do |sfields| %>
              <% site = sfields.object %>
              <div class="govuk-checkboxes__item">
                <%= sfields.check_box "selected", checked: course.has_site?(site), class: "govuk-checkboxes__input" %>
                <%= sfields.label "selected", class: "govuk-label govuk-checkboxes__label"  do %>
                  <strong data-qa="site__name"><%= site.location_name %></strong>
                <% end %>
                <span class="govuk-hint govuk-checkboxes__hint">
                  <%= site.full_address %>
                </span>
              </div>
            <% end %>
          </div>
        </div>
      </fieldset>
    <% end %>
  <% end %>
<% end %>